# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # Declare a dependency on the welcome-orb
  # welcome: circleci/welcome-orb@0.4.1

# Orchestrate or schedule a set of jobs

jobs:
  configure_infrastructure: 
   docker:
    - image: python:3.9-alpine3.16
   steps:
    - checkout
    - add_ssh_keys:
            # You can get this ID in the section where you registered the SSH Key
            fingerprints: ["96:ff:39:63:e7:c5:20:79:2b:5d:b7:a2:27:33:2f:d7"] 
    - run:
        name: Install Ansible
        command: |
          apk add --update ansible
    - run:
        name: Run Playbook and Configure server
        command: |
          ansible-playbook -i inventory main.yml --private-key create-infta-key


workflows:
  my_workflow:
      jobs:
        - configure_infrastructure
